# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.resize(542, 308)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/images/docdoc_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HelpDialog.setWindowIcon(icon)
        HelpDialog.setStyleSheet("QDialog {background-color:rgb(249, 249, 249)}\n"
"QPushButton {background-color:rgb(249, 249, 249);  color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QPushButton:hover {background-color:rgb(230, 230, 230);}\n"
"QPushButton:pressed {background-color:rgb(212, 212, 212);}\n"
"QLineEdit {padding: 5; border-radius: 10px;border: 1px solid #CCCCCC;font: 25 14pt \"Yu Gothic UI Light\";}\n"
"QLabel {color:rgb(28, 94, 217,);}")
        self.quit_button = QtWidgets.QPushButton(HelpDialog)
        self.quit_button.setGeometry(QtCore.QRect(200, 220, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.quit_button.setFont(font)
        self.quit_button.setObjectName("quit_button")
        self.help_field = QtWidgets.QLabel(HelpDialog)
        self.help_field.setGeometry(QtCore.QRect(20, 20, 501, 181))
        self.help_field.setStyleSheet("font: 25 16pt \"Yu Gothic UI Light\"; padding: 8; color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC; background-color:rgb(249, 249, 249);")
        self.help_field.setText("")
        self.help_field.setAlignment(QtCore.Qt.AlignCenter)
        self.help_field.setWordWrap(True)
        self.help_field.setObjectName("help_field")

        self.retranslateUi(HelpDialog)
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "Help"))
        self.quit_button.setText(_translate("HelpDialog", "Понятно"))
