# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExpertMedicSystemForm(object):
    def setupUi(self, ExpertMedicSystemForm):
        ExpertMedicSystemForm.setObjectName("ExpertMedicSystemForm")
        ExpertMedicSystemForm.resize(800, 600)
        ExpertMedicSystemForm.setMinimumSize(QtCore.QSize(800, 600))
        ExpertMedicSystemForm.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/images/docdoc_window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExpertMedicSystemForm.setWindowIcon(icon)
        ExpertMedicSystemForm.setStyleSheet("QMainWindow {background-color:rgb(249, 249, 249)}\n"
"QPushButton {background-color:rgb(249, 249, 249);  color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC;}\n"
"QPushButton:hover {background-color:rgb(230, 230, 230);}\n"
"QPushButton:pressed {background-color:rgb(212, 212, 212);}\n"
"QLineEdit {padding: 5; border-radius: 10px;border: 1px solid #CCCCCC;font: 25 14pt \"Yu Gothic UI Light\";}\n"
"QLabel {color:rgb(28, 94, 217,);}")
        ExpertMedicSystemForm.setIconSize(QtCore.QSize(24, 24))
        ExpertMedicSystemForm.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(ExpertMedicSystemForm)
        self.centralwidget.setObjectName("centralwidget")
        self.question_field = QtWidgets.QLabel(self.centralwidget)
        self.question_field.setGeometry(QtCore.QRect(240, 30, 551, 141))
        self.question_field.setStyleSheet("font: 25 26pt \"Yu Gothic UI Light\";")
        self.question_field.setAlignment(QtCore.Qt.AlignCenter)
        self.question_field.setWordWrap(True)
        self.question_field.setObjectName("question_field")
        self.yes_button = QtWidgets.QPushButton(self.centralwidget)
        self.yes_button.setGeometry(QtCore.QRect(320, 190, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yes_button.setFont(font)
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(self.centralwidget)
        self.no_button.setGeometry(QtCore.QRect(520, 190, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.no_button.setFont(font)
        self.no_button.setObjectName("no_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("static/images/docdoc_label.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(20, 190, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.restart_button.setFont(font)
        self.restart_button.setObjectName("restart_button")
        self.result_field = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_field.setGeometry(QtCore.QRect(20, 270, 761, 311))
        self.result_field.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.result_field.setStyleSheet("font: 25 18pt \"Yu Gothic UI Light\"; padding: 8; color:rgb(28, 94, 217); border-radius: 10px;border: 1px solid #CCCCCC; background-color:rgb(249, 249, 249);")
        self.result_field.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_field.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.result_field.setObjectName("result_field")
        self.result_help_button = QtWidgets.QPushButton(self.centralwidget)
        self.result_help_button.setGeometry(QtCore.QRect(730, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result_help_button.setFont(font)
        self.result_help_button.setObjectName("result_help_button")
        self.question_help_button = QtWidgets.QPushButton(self.centralwidget)
        self.question_help_button.setGeometry(QtCore.QRect(730, 10, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.question_help_button.setFont(font)
        self.question_help_button.setObjectName("question_help_button")
        self.hello_field = QtWidgets.QLabel(self.centralwidget)
        self.hello_field.setGeometry(QtCore.QRect(40, 300, 721, 251))
        self.hello_field.setStyleSheet("font: 25 22pt \"Yu Gothic UI Light\";")
        self.hello_field.setScaledContents(False)
        self.hello_field.setAlignment(QtCore.Qt.AlignCenter)
        self.hello_field.setWordWrap(True)
        self.hello_field.setObjectName("hello_field")
        self.yes_button.raise_()
        self.no_button.raise_()
        self.question_field.raise_()
        self.label.raise_()
        self.restart_button.raise_()
        self.result_field.raise_()
        self.result_help_button.raise_()
        self.question_help_button.raise_()
        self.hello_field.raise_()
        ExpertMedicSystemForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExpertMedicSystemForm)
        QtCore.QMetaObject.connectSlotsByName(ExpertMedicSystemForm)

    def retranslateUi(self, ExpertMedicSystemForm):
        _translate = QtCore.QCoreApplication.translate
        ExpertMedicSystemForm.setWindowTitle(_translate("ExpertMedicSystemForm", "Medical expert system"))
        self.question_field.setText(_translate("ExpertMedicSystemForm", "Вопрос"))
        self.yes_button.setText(_translate("ExpertMedicSystemForm", "Да"))
        self.no_button.setText(_translate("ExpertMedicSystemForm", "Нет"))
        self.restart_button.setText(_translate("ExpertMedicSystemForm", "Начать заново"))
        self.result_field.setHtml(_translate("ExpertMedicSystemForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Light\'; font-size:18pt; font-weight:24; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.result_help_button.setText(_translate("ExpertMedicSystemForm", "?"))
        self.question_help_button.setText(_translate("ExpertMedicSystemForm", "?"))
        self.hello_field.setText(_translate("ExpertMedicSystemForm", "Добро пожаловать в медицинскую экспертную систему!\n"
"Здесь будут предполагаемые в ходе опроса заболевания и конечный результат."))
